workflows:
  android-workflow:
    name: Android Debug Build
    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
    android:
      gradle: "8.2"
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
