workflows:
  android-workflow:
    name: Android Debug Build
    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
