workflows:
  android-workflow:
    name: Android Debug Build
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
